' Styling
' ##################################
!define TECHN_FONT_SIZE 12
!define ELEMENT_FONT_COLOR #FFFFFF

skinparam defaultTextAlignment center
skinparam wrapWidth 400
skinparam maxMessageSize 150
skinparam StereotypeAlignment right

skinparam Arrow {
    Color #000000
    FontColor #000000
    FontSize 12
}
