' Layout
' ##################################
!unquoted procedure LAYOUT_AS_SKETCH()
    skinparam backgroundColor #EEEBDC
    skinparam handwritten true
    skinparam defaultFontName "Comic Sans MS"
    center footer <font color=red>Warning:</font> Created for discussion, needs to be validated
!endprocedure
!unquoted procedure LAYOUT_TOP_DOWN()
	top to bottom direction
!endprocedure
!unquoted procedure LAYOUT_LEFT_RIGHT()
	left to right direction
!endprocedure

' Layout Helpers
' ##################################
!unquoted procedure Lay_D(e_from, e_to)
	e_from -[hidden]D- e_to
!endprocedure
!unquoted procedure Lay_U(e_from, e_to)
	e_from -[hidden]U- e_to
!endprocedure
!unquoted procedure Lay_R(e_from, e_to)
	e_from -[hidden]R- e_to
!endprocedure
!unquoted procedure Lay_L(e_from, e_to)
	e_from -[hidden]L- e_to
!endprocedure

