' Styling
' ##################################

skinparam rectangle {
    Shadowing true
    RoundCorner 6
    BorderColor<<system-other>> darkgray
    BackgroundColor<<system-other>> lightgray
    BorderColor<<system-of-interest>> #504661
    BackgroundColor<<system-of-interest>> #B19CD9
    DiagonalCorner<<system-of-interest>> 12
    BorderColor<<system-our>> #4c6263
    BackgroundColor<<system-our>> #A9DCDF
    BorderColor<<system-placeholder>> black
    BackgroundColor<<system-placeholder>> #eeeeee
    BorderStyle<<system-placeholder>> dotted
    BackgroundColor<<system-support>> #FFFF00
    BorderColor<<system-support>> black
}
skinparam actor<<system-role>> {
    BorderColor #777777
    BackgroundColor lightgray
}

hide <<system-other>> stereotype
hide <<system-of-interest>> stereotype
hide <<system-our>> stereotype
hide <<system-role>> stereotype
hide <<system-placeholder>> stereotype
hide <<system-support>> stereotype

' Elements
' ##################################
'System Elements
!define System_Other(e_alias, e_label) rectangle "e_label" <<system-other>> as e_alias
!define System_OfInterest(e_alias, e_label) rectangle "e_label" <<system-of-interest>> as e_alias
!define System_Our(e_alias, e_label) rectangle "e_label" <<system-our>> as e_alias
!define System_Role(e_alias, e_label) actor "e_label" <<system-role>> as e_alias
!define System_Placeholder(e_alias, e_label) rectangle "e_label" <<system-placeholder>> as e_alias
!define System_Support(e_alias, e_label) rectangle "e_label" <<system-support>> as e_alias
